language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t marilita83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marilita83/react-test npm test -- --coverage

after_success:
  - docker build -t marilita83/multi-client ./client
  - docker build -t marilita83/multi-nginx ./nginx
  - docker build -t marilita83/multi-server ./server
  - docker build -t marilita83/multi-worker ./worker
#Log in to the docker CLI and push the images to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push marilita83/multi-client
  - docker push marilita83/multi-nginx
  - docker push marilita83/multi-server
  - docker push marilita83/multi-worker
