sudo: required
services:
  - docker

before_install:
  - docker build -t marilita/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marilita/react-test npm test -- --coverage

after_success:
  - docker build -t marilita/multi-client ./client
  - docker build -t marilita/multi-nginx ./nginx
  - docker build -t marilita/multi-server ./server
  - docker build -t marilita/multi-worker ./worker