version: "3"
services:
  client:
    image: "marilita83/multi-client"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: client
  api:
    image: "marilita83/multi-server"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "marilita83/multi-worker"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "marilita83/multi-nginx"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: nginx
    ports:
      - "80:80"